---
- name: Configure webserver with Nginx
  hosts: test
  become: true

  vars:
    tls_dir: /etc/nginx/ssl/
    key_file: nginx.key
    cert_file: nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Install nginx
      package: >
          name=nginx
          update_cache=yes

    - name: Create TLS dir
      file:
        path: "{{ tls_dir }}"
        state: directory
        mode: 0750
      notify: Restart nginx


    - name: Copy TLS files
      copy:
        src: "{{ item }}"
        dest: "{{ tls_dir }}"
      loop:
        - "{{ key_file }}"
        - "{{ cert_file }}"

      notify: Restart nginx


    - name: Manage template of nginx config
      template:
        src: nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: '0644'
      notify: Restart nginx

    - name: Enable config
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: Copy index.html
      template: >
        src=index.html.j2
        dest=/usr/share/nginx/html/index.html
